name: Deploy Spring Boot to AWS EC2

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_NAME: motus_project
  BUCKET_NAME: motus-buket
  AWS_REGION: ap-northeast-2
  CODE_DEPLOY_APP_NAME: motus-buket
  DEPLOYMENT_GROUP_NAME: motus_CICD_group

jobs:
  deploy:
    needs: build # 빌드 작업이 성공적으로 완료되어야만 배포 작업을 실행
    runs-on: ubuntu-latest
    steps:
      - name: Make Zip File
        run: zip -qq -r ./$GITHUB_SHA.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.CICD_ACCESS_KEY}}
          aws-secret-access-key: ${{ secrets.CICD_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload Zip File to S3
        run: aws s3 cp --region ${{ env.AWS_REGION }} ./$GITHUB_SHA.zip s3://$BUCKET_NAME/$PROJECT_NAME/$GITHUB_SHA.zip

      - name: Code Deploy to EC2
        run: aws deploy create-deployment --application-name $CODE_DEPLOY_APP_NAME --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name $DEPLOYMENT_GROUP_NAME --s3-location bucket=$BUCKET_NAME,bundleType=zip,key=$PROJECT_NAME/$GITHUB_SHA.zip